#!/usr/bin/env bash
#Bash script that:
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
file='/var/run/myscript.pid'

cleanup()
{
    rm -f "$file"
    exit 0
}

trap 'cleanup' SIGQUIT
trap '{ echo I hate the kill command; cleanup; }' SIGTERM
trap 'echo Y U no love me?!' SIGINT

echo "$$" > "$file"

while true;
do
    echo "To infinity and beyond"
    sleep 2
done
