#!/usr/bin/env bash
#Bash script that groups visitors by IP and HTTP status code, and displays this data.
awk '{ match($0, /[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/); ip = substr($0, RSTART, RLENGTH); match($0, / [0-9]+ /); code = substr($0, RSTART, RLENGTH); print ip, code }' apache-access.log | sort | uniq -c | sort -nr | awk '{ print $1, $2, $3 }'
